import type { NewsItem } from "./types"

export const newsData: NewsItem[] = [
  {
    id: "1",
    title: "Bihar Government Announces Major Infrastructure Development Project",
    summary:
      "The state government has approved a 5000 crore infrastructure project to improve connectivity across rural areas.",
    image: "/bihar-infrastructure-development-project-governmen.jpg",
    category: "Bihar",
    date: "2025-11-10",
    source: "Bihar News Bureau",
  },
  {
    id: "2",
    title: "India Launches New Space Mission to Study Climate Patterns",
    summary: "ISRO successfully launches satellite to monitor and analyze climate patterns across South Asia.",
    image: "/india-space-mission-satellite-climate-monitoring.jpg",
    category: "India",
    date: "2025-11-09",
    source: "India Today",
  },
  {
    id: "3",
    title: "World Leaders Meet for Climate Summit 2025",
    summary: "Global leaders gather to discuss strategies for combating climate change and reducing carbon emissions.",
    image: "/world-climate-summit-leaders-meeting-conference.jpg",
    category: "World",
    date: "2025-11-08",
    source: "Reuters",
  },
  {
    id: "4",
    title: "New Political Alliance Formed in Bihar Assembly",
    summary: "Political parties unite to form a new coalition government focused on rural development.",
    image: "/bihar-politics-government-coalition-assembly.jpg",
    category: "Politics",
    date: "2025-11-07",
    source: "PTI",
  },
  {
    id: "5",
    title: "India Cricket Team Wins Test Series Against Australia",
    summary: "Indian cricket team secures a historic victory with a 3-1 series win in Australia.",
    image: "/india-cricket-team-test-match-australia-victory.jpg",
    category: "Sports",
    date: "2025-11-06",
    source: "Sports Central",
  },
  {
    id: "6",
    title: "Tech Giants Announce Breakthrough in Quantum Computing",
    summary: "Leading tech companies reveal significant advances in quantum computing technology.",
    image: "/quantum-computing-technology-breakthrough-tech-inn.jpg",
    category: "Technology",
    date: "2025-11-05",
    source: "Tech News Daily",
  },
  {
    id: "7",
    title: "Bollywood Stars Gather for Film Festival 2025",
    summary: "Major Indian film festival showcases latest movies and celebrates cinema excellence.",
    image: "/bollywood-film-festival-entertainment-celebrities.jpg",
    category: "Entertainment",
    date: "2025-11-04",
    source: "Entertainment Weekly",
  },
  {
    id: "8",
    title: "Bihar Agricultural Department Launches New Farming Initiative",
    summary: "State department introduces modern farming techniques to increase agricultural productivity.",
    image: "/bihar-agriculture-farming-initiative-modern-techni.jpg",
    category: "Bihar",
    date: "2025-11-03",
    source: "Bihar News Bureau",
  },
  {
    id: "9",
    title: "India-China Trade Relations Show Signs of Improvement",
    summary: "Bilateral talks result in new trade agreements and economic cooperation initiatives.",
    image: "/india-china-trade-relations-economy-cooperation.jpg",
    category: "India",
    date: "2025-11-02",
    source: "Economic Times",
  },
  {
    id: "10",
    title: "Global Economic Forum Discusses Future Challenges",
    summary: "World economic leaders convene to address inflation, recession, and market stability concerns.",
    image: "/global-economic-forum-conference-leaders-business.jpg",
    category: "World",
    date: "2025-11-01",
    source: "Financial Times",
  },
  {
    id: "11",
    title: "Election Commission Announces New Voting Procedures",
    summary: "Major changes implemented in voting system to ensure transparency and efficiency.",
    image: "/election-voting-procedure-announcement-democracy.jpg",
    category: "Politics",
    date: "2025-10-31",
    source: "Election Commission",
  },
  {
    id: "12",
    title: "Olympic Preparations Begin for 2026 Games",
    summary: "Countries start training and preparing athletes for the upcoming Olympic competition.",
    image: "/olympic-games-2026-preparation-athletes-training.jpg",
    category: "Sports",
    date: "2025-10-30",
    source: "Olympic News",
  },
]
